"""data type changes in userhistory table.

Revision ID: 778901362c7d
Revises: 9c051a96f168
Create Date: 2026-05-10 13:48:52.912493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '778901362c7d'
down_revision: Union[str, Sequence[str], None] = '9c051a96f168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userhistory', 'temperature',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="temperature::double precision")
    op.alter_column('userhistory', 'feels_like',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False,
                postgresql_using="feels_like::double precision")
    op.alter_column('userhistory', 'humidity',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="humidity::double precision")
    op.alter_column('userhistory', 'wind',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="wind::double precision")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userhistory', 'wind',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('userhistory', 'humidity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('userhistory', 'feels_like',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('userhistory', 'temperature',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
