"""add the new city_name column in UserHistory table.

Revision ID: d233eb9684bf
Revises: f5af28b36f91
Create Date: 2026-02-12 08:45:12.908746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd233eb9684bf'
down_revision: Union[str, Sequence[str], None] = 'f5af28b36f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userhistory', sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userhistory', 'city_name')
    # ### end Alembic commands ###
