"""new UserHistory table add in database.py

Revision ID: e03c312c71be
Revises: 67fdae344c50
Create Date: 2026-02-11 20:46:29.650725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e03c312c71be'
down_revision: Union[str, Sequence[str], None] = '67fdae344c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feels_like', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('humidity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weather', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userhistory')
    # ### end Alembic commands ###
