"""update the data type of time column in UserHistory table

Revision ID: f5af28b36f91
Revises: e03c312c71be
Create Date: 2026-02-12 08:15:15.772187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5af28b36f91'
down_revision: Union[str, Sequence[str], None] = 'e03c312c71be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userhistory', 'time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_foreign_key(None, 'userhistory', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userhistory', type_='foreignkey')
    op.alter_column('userhistory', 'time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
